@startuml

hide empty members
hide circle

skinparam class {
    BackgroundColor<<Decided>> #028A0F
    BackgroundColor<<Rejected>> #E3242B
}

!procedure decided($name, $description)
class $name <<Decided>>  {
    $description
}
!endprocedure

!procedure rejected($name, $description)
class $name <<Rejected>>  {
    $description
}
!endprocedure



class Serverside_Programmeertaal
decided("PHP", "PHP 7.4 wordt gebruikt als taal om\nde applicatie in te schrijven")
Serverside_Programmeertaal <-- PHP

class "Front-end Styling Taal"
decided("SCSS", "SCSS wordt gebruikt voor\nde opmaak van de applicatie")
"Front-end Styling Taal" <-- SCSS



@enduml