@startuml

node browser
node server {
    artifact website {
        component core
        component modules

    }
    database database
}

browser -- core
core -- modules
core -- database
modules -l- database


@enduml